#!/bin/bash

wget -lo terraform https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_linux_amd64.zip
unzip terraform_1.9.2_linux_amd64.zip 
mv terraform_1.9.2_linux_amd64 /usr/local/bin/terraform
